---
name: BanItem
author: LDX
version: 2.3.4
api:
- 4.0.0
main: LDX\BanItem\Main
load: POSTWORLD
description: A BanItem Plugin edited by amit
website: https://github.com/LDX-MCPE/BanItem
extensions:
  Core: '>=8.0'
commands:
  banitem:
    description: BanItem main command
    usage: "/banitem <ban/unban/report> [ID[:Damage]]"
    permission: banitem.command.banitem
permissions:
  banitem:
    description: "Allows access to all BanItem features."
    default: op
  banitem.bypass:
    description: "Allows access to using banned items."
    default: op
  banitem.command:
    description: "Allows access to all BanItem commands."
    default: op
  banitem.command.banitem:
    description: "Allows access to the item command."
    default: op
...
